### ISSUE TITLE
Support for React 16

### ISSUE THREAD

**Issue by MiaXIA** [JedWatson/react-domify#4]
I used it for my project, but recently I upgraded my project to React 16, and this package has the error: "TypeError: React.createClass is not a function". I think it is because React 16 remove the function of createClass. Can we upgrade this package like declaring React.Component so that it can support React 16? Thank you!

**Comment by MiaXIA** [comment]
I simply change the way claiming React Class as 
`class DOMify extends React.Component {
    render() {
        return (
            <div className={this.props.className} style={this.props.style}>
                {transform(this.props.value)}
            </div>
        )
    }
}`
And it will works fine with React 16 (In my code, it is ^16.7.0), if you want, I can create the PR and merge it into your package to make this package works with latest React version.

**Comment by MiaXIA** [comment]
I simply change the way claiming React Class as
`class DOMify extends Component {`
`    render() {`
`        return (`
`            <div className={this.props.className} style={this.props.style}>`
`                {transform(this.props.value)}`
`            </div>`
`        )`
`    }`
`}`
And it will works fine with React 16 (In my code, it is ^16.7.0), if you want, I can create the PR and merge it into your package to make this package works with latest React version.
